name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.7.3
          cache: true

      - name: Install socat
        run: sudo apt-get update && sudo apt-get install -y socat

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Configure project
        run: cmake --preset=dev

      - name: Build project
        run: cmake --build ./build-dev

      - name: Test
        run: ./run_test.sh build-dev
        env:
          QT_QPA_PLATFORM: "offscreen"
